spring.application.name=cron-email

# Datasource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/cron_email
spring.datasource.username=root
spring.datasource.password=paudel
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

#JWT Secret key
app.jwt.secret-key=hello-world-this-is-a-secret-key
app.jwt.expiration-time=3600000
